"""initial schema

Revision ID: 486090cfcf32
Revises:
Create Date: 2026-08-30 18:06:15.674937
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "486090cfcf32"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_user",
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("username_normalized", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DISABLED",
                name="admin_user_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("auth_version", sa.Integer(), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("auth_version >= 1", name=op.f("ck_admin_user_auth_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_user")),
        sa.UniqueConstraint("username_normalized", name=op.f("uq_admin_user_username_normalized")),
    )
    with op.batch_alter_table("admin_user", schema=None) as batch_op:
        batch_op.create_index("ix_admin_user_status", ["status"], unique=False)

    op.create_table(
        "auth_login_throttle",
        sa.Column(
            "dimension",
            sa.Enum(
                "ACCOUNT",
                "SOURCE",
                name="login_throttle_dimension",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_login_throttle")),
        sa.UniqueConstraint("dimension", "key_hash", name=op.f("uq_auth_login_throttle_dimension")),
    )
    with op.batch_alter_table("auth_login_throttle", schema=None) as batch_op:
        batch_op.create_index("ix_auth_login_throttle_blocked", ["blocked_until"], unique=False)

    op.create_table(
        "rbac_permission",
        sa.Column("code", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rbac_permission")),
        sa.UniqueConstraint("code", name=op.f("uq_rbac_permission_code")),
    )
    op.create_table(
        "rbac_role",
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rbac_role")),
        sa.UniqueConstraint("code", name=op.f("uq_rbac_role_code")),
    )
    op.create_table(
        "workspace",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace")),
        sa.UniqueConstraint("slug", name=op.f("uq_workspace_slug")),
    )
    op.create_table(
        "acl_policy_state",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_acl_policy_state_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_acl_policy_state")),
    )
    op.create_table(
        "admin_session",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column("auth_version", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=120), nullable=True),
        sa.Column("source_key_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin_user.id"],
            name=op.f("fk_admin_session_user_id_admin_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_admin_session_token_hash")),
    )
    with op.batch_alter_table("admin_session", schema=None) as batch_op:
        batch_op.create_index(
            "ix_admin_session_expiry", ["idle_expires_at", "absolute_expires_at"], unique=False
        )
        batch_op.create_index(
            "ix_admin_session_user_active", ["user_id", "revoked_at"], unique=False
        )

    op.create_table(
        "audit_event",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("object_type", sa.String(length=80), nullable=False),
        sa.Column("object_id", sa.String(length=255), nullable=False),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_audit_event_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_event_trace_created", ["trace_id", "created_at"], unique=False
        )

    op.create_table(
        "auth_bootstrap_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("token_fingerprint", sa.String(length=16), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["admin_user.id"],
            name=op.f("fk_auth_bootstrap_state_owner_user_id_admin_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_bootstrap_state")),
        sa.UniqueConstraint("owner_user_id", name=op.f("uq_auth_bootstrap_state_owner_user_id")),
    )
    op.create_table(
        "gewe_connection",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("api_base_url", sa.String(length=500), nullable=False),
        sa.Column("token_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("token_fingerprint", sa.String(length=16), nullable=False),
        sa.Column(
            "callback_mode",
            sa.Enum(
                "MANUAL",
                "PLATFORM_MANAGED",
                name="callback_management_mode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("callback_secret_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("callback_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("callback_expected_url_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("callback_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_callback_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_callback_error", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DISABLED",
                "ERROR",
                name="gewe_connection_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_gewe_connection_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gewe_connection")),
        sa.UniqueConstraint(
            "callback_secret_hash", name=op.f("uq_gewe_connection_callback_secret_hash")
        ),
        sa.UniqueConstraint("workspace_id", "name", name=op.f("uq_gewe_connection_workspace_id")),
    )
    op.create_table(
        "plugin",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("plugin_id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_plugin_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin")),
        sa.UniqueConstraint("workspace_id", "plugin_id", name=op.f("uq_plugin_workspace_id")),
    )
    op.create_table(
        "policy_decision",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=True),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column(
            "effect",
            sa.Enum(
                "ALLOW",
                "ASK",
                "DENY",
                name="policy_decision_effect",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "request_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "matched_rule_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_policy_decision_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_decision")),
    )
    with op.batch_alter_table("policy_decision", schema=None) as batch_op:
        batch_op.create_index(
            "ix_policy_decision_trace_created", ["trace_id", "created_at"], unique=False
        )

    op.create_table(
        "principal",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "principal_type",
            sa.Enum(
                "ADMIN_USER",
                "CONTACT",
                "GROUP_MEMBER",
                "CONNECTOR",
                "PLUGIN",
                "TASK_AGENT",
                "AUTOMATION",
                "SYSTEM",
                name="principal_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_principal_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_principal")),
        sa.UniqueConstraint(
            "workspace_id", "principal_type", "external_id", name=op.f("uq_principal_workspace_id")
        ),
    )
    with op.batch_alter_table("principal", schema=None) as batch_op:
        batch_op.create_index(
            "ix_principal_workspace_active", ["workspace_id", "active"], unique=False
        )

    op.create_table(
        "rbac_role_permission",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["rbac_permission.id"],
            name=op.f("fk_rbac_role_permission_permission_id_rbac_permission"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["rbac_role.id"],
            name=op.f("fk_rbac_role_permission_role_id_rbac_role"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_rbac_role_permission")),
    )
    op.create_table(
        "rbac_user_role",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["rbac_role.id"],
            name=op.f("fk_rbac_user_role_role_id_rbac_role"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin_user.id"],
            name=op.f("fk_rbac_user_role_user_id_admin_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_rbac_user_role")),
    )
    op.create_table(
        "acl_rule",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=True),
        sa.Column(
            "scope_type",
            sa.Enum(
                "WORKSPACE",
                "BOT_ACCOUNT",
                "CHATROOM",
                "CONTACT",
                name="acl_scope_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("scope_id", sa.String(length=255), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum(
                "CATEGORY",
                "PLUGIN",
                "COMMAND",
                "TOOL",
                "AGENT",
                "CAPABILITY",
                name="acl_resource_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column(
            "effect",
            sa.Enum(
                "ALLOW", "ASK", "DENY", name="acl_effect", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("membership_epoch", sa.Integer(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principal.id"],
            name=op.f("fk_acl_rule_principal_id_principal"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_acl_rule_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acl_rule")),
    )
    with op.batch_alter_table("acl_rule", schema=None) as batch_op:
        batch_op.create_index(
            "ix_acl_rule_lookup",
            ["workspace_id", "resource_type", "resource_id", "revoked_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_acl_rule_scope", ["workspace_id", "scope_type", "scope_id"], unique=False
        )

    op.create_table(
        "auth_security_event",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "SUCCESS",
                "DENIED",
                "RATE_LIMITED",
                "REVOKED",
                name="auth_event_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("username_normalized", sa.String(length=80), nullable=True),
        sa.Column("source_key_hash", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["admin_session.id"],
            name=op.f("fk_auth_security_event_session_id_admin_session"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin_user.id"],
            name=op.f("fk_auth_security_event_user_id_admin_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_security_event")),
    )
    with op.batch_alter_table("auth_security_event", schema=None) as batch_op:
        batch_op.create_index("ix_auth_security_event_created", ["created_at"], unique=False)

    op.create_table(
        "bot_account",
        sa.Column("gewe_connection_id", sa.Uuid(), nullable=False),
        sa.Column("app_id", sa.String(length=255), nullable=False),
        sa.Column("wxid", sa.String(length=255), nullable=True),
        sa.Column("alias", sa.String(length=255), nullable=True),
        sa.Column("nickname", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("pending_login_uuid", sa.String(length=255), nullable=True),
        sa.Column("qr_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status_error", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "UNBOUND",
                "QR_PENDING",
                "SCANNED",
                "ONLINE",
                "OFFLINE",
                "RECONNECTING",
                "NEED_QR",
                "DISABLED",
                name="bot_account_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("logged_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_online_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gewe_connection_id"],
            ["gewe_connection.id"],
            name=op.f("fk_bot_account_gewe_connection_id_gewe_connection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_account")),
        sa.UniqueConstraint(
            "gewe_connection_id", "app_id", name=op.f("uq_bot_account_gewe_connection_id")
        ),
    )
    with op.batch_alter_table("bot_account", schema=None) as batch_op:
        batch_op.create_index(
            "ix_bot_account_connection_status", ["gewe_connection_id", "status"], unique=False
        )

    op.create_table(
        "plugin_deployment",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("plugin_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "STOPPED",
                "STARTING",
                "RUNNING",
                "DRAINING",
                "FAILED",
                "QUARANTINED",
                name="plugin_deployment_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("active_revision_id", sa.Uuid(), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plugin_id"],
            ["plugin.id"],
            name=op.f("fk_plugin_deployment_plugin_id_plugin"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_plugin_deployment_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_deployment")),
        sa.UniqueConstraint("workspace_id", "name", name=op.f("uq_plugin_deployment_workspace_id")),
    )
    op.create_table(
        "plugin_package_version",
        sa.Column("plugin_id", sa.Uuid(), nullable=False),
        sa.Column("semantic_version", sa.String(length=80), nullable=False),
        sa.Column("package_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("package_path", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "AVAILABLE",
                "RETIRED",
                "REJECTED",
                name="plugin_package_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plugin_id"],
            ["plugin.id"],
            name=op.f("fk_plugin_package_version_plugin_id_plugin"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_package_version")),
        sa.UniqueConstraint(
            "package_sha256", name=op.f("uq_plugin_package_version_package_sha256")
        ),
        sa.UniqueConstraint(
            "plugin_id", "semantic_version", name=op.f("uq_plugin_package_version_plugin_id")
        ),
    )
    op.create_table(
        "webhook_inbox",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("gewe_connection_id", sa.Uuid(), nullable=False),
        sa.Column("app_id", sa.String(length=255), nullable=False),
        sa.Column("new_msg_id", sa.String(length=255), nullable=True),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "NORMALIZED",
                "DISPATCHING",
                "DISPATCHED",
                "FAILED",
                "IGNORED_SELF",
                name="webhook_inbox_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_detail", sa.String(length=1000), nullable=True),
        sa.Column("dispatch_attempt_count", sa.Integer(), nullable=False),
        sa.Column("dispatch_available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gewe_connection_id"],
            ["gewe_connection.id"],
            name=op.f("fk_webhook_inbox_gewe_connection_id_gewe_connection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_inbox")),
        sa.UniqueConstraint(
            "provider",
            "gewe_connection_id",
            "app_id",
            "dedup_key",
            name=op.f("uq_webhook_inbox_provider"),
        ),
    )
    with op.batch_alter_table("webhook_inbox", schema=None) as batch_op:
        batch_op.create_index(
            "ix_webhook_inbox_status_received",
            ["status", "dispatch_available_at", "created_at"],
            unique=False,
        )

    op.create_table(
        "chatroom",
        sa.Column("bot_account_id", sa.Uuid(), nullable=False),
        sa.Column("chatroom_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("owner_wxid", sa.String(length=255), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=True),
        sa.Column("discovered_from", sa.String(length=32), nullable=False),
        sa.Column("placeholder", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bot_account_id"],
            ["bot_account.id"],
            name=op.f("fk_chatroom_bot_account_id_bot_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chatroom")),
        sa.UniqueConstraint(
            "bot_account_id", "chatroom_id", name=op.f("uq_chatroom_bot_account_id")
        ),
    )
    op.create_table(
        "contact",
        sa.Column("bot_account_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("contact_type", sa.String(length=32), nullable=False),
        sa.Column("nickname", sa.String(length=255), nullable=True),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bot_account_id"],
            ["bot_account.id"],
            name=op.f("fk_contact_bot_account_id_bot_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
        sa.UniqueConstraint(
            "bot_account_id", "external_id", name=op.f("uq_contact_bot_account_id")
        ),
    )
    op.create_table(
        "normalized_event",
        sa.Column("webhook_inbox_id", sa.Uuid(), nullable=False),
        sa.Column("bot_account_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "conversation_type",
            sa.Enum(
                "PRIVATE",
                "GROUP",
                "SYSTEM",
                "UNKNOWN",
                name="conversation_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("conversation_id", sa.String(length=255), nullable=True),
        sa.Column("actor_wxid", sa.String(length=255), nullable=True),
        sa.Column("to_wxid", sa.String(length=255), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("is_self", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "content",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("raw_ref", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bot_account_id"],
            ["bot_account.id"],
            name=op.f("fk_normalized_event_bot_account_id_bot_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["webhook_inbox_id"],
            ["webhook_inbox.id"],
            name=op.f("fk_normalized_event_webhook_inbox_id_webhook_inbox"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_event")),
        sa.UniqueConstraint("webhook_inbox_id", name=op.f("uq_normalized_event_webhook_inbox_id")),
    )
    with op.batch_alter_table("normalized_event", schema=None) as batch_op:
        batch_op.create_index(
            "ix_normalized_event_conversation", ["bot_account_id", "conversation_id"], unique=False
        )

    op.create_table(
        "outbox_message",
        sa.Column("bot_account_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("target_wxid", sa.String(length=255), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "authorization_context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CLAIMED",
                "SENDING",
                "SENT",
                "FAILED_RETRYABLE",
                "FAILED_FINAL",
                "UNKNOWN",
                "CANCELLED",
                name="outbox_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bot_account_id"],
            ["bot_account.id"],
            name=op.f("fk_outbox_message_bot_account_id_bot_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_message")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_outbox_message_idempotency_key")),
    )
    with op.batch_alter_table("outbox_message", schema=None) as batch_op:
        batch_op.create_index(
            "ix_outbox_status_available", ["status", "available_at"], unique=False
        )

    op.create_table(
        "plugin_deployment_revision",
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("package_version_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("config_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "scope",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "grants",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["plugin_deployment.id"],
            name=op.f("fk_plugin_deployment_revision_deployment_id_plugin_deployment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["package_version_id"],
            ["plugin_package_version.id"],
            name=op.f("fk_plugin_deployment_revision_package_version_id_plugin_package_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_deployment_revision")),
        sa.UniqueConstraint(
            "deployment_id",
            "revision_number",
            name=op.f("uq_plugin_deployment_revision_deployment_id"),
        ),
    )
    with op.batch_alter_table("plugin_deployment_revision", schema=None) as batch_op:
        batch_op.create_index("ix_plugin_revision_package", ["package_version_id"], unique=False)

    op.create_table(
        "chatroom_membership",
        sa.Column("chatroom_id", sa.Uuid(), nullable=False),
        sa.Column("member_wxid", sa.String(length=255), nullable=False),
        sa.Column("membership_epoch", sa.Integer(), nullable=False),
        sa.Column("nickname", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("inviter_wxid", sa.String(length=255), nullable=True),
        sa.Column("member_flag", sa.BigInteger(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chatroom_id"],
            ["chatroom.id"],
            name=op.f("fk_chatroom_membership_chatroom_id_chatroom"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chatroom_membership")),
        sa.UniqueConstraint(
            "chatroom_id",
            "member_wxid",
            "membership_epoch",
            name=op.f("uq_chatroom_membership_chatroom_id"),
        ),
    )
    with op.batch_alter_table("chatroom_membership", schema=None) as batch_op:
        batch_op.create_index(
            "ix_membership_active_member", ["chatroom_id", "member_wxid", "left_at"], unique=False
        )

    op.create_table(
        "plugin_revision_activation",
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("activation_epoch", sa.Integer(), nullable=False),
        sa.Column("fencing_token", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CANDIDATE",
                "STARTING",
                "READY",
                "ACTIVE",
                "DRAINING",
                "STOPPED",
                "FAILED",
                name="plugin_activation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_detail", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["plugin_deployment.id"],
            name=op.f("fk_plugin_revision_activation_deployment_id_plugin_deployment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["plugin_deployment_revision.id"],
            name=op.f("fk_plugin_revision_activation_revision_id_plugin_deployment_revision"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_revision_activation")),
        sa.UniqueConstraint(
            "deployment_id",
            "activation_epoch",
            name=op.f("uq_plugin_revision_activation_deployment_id"),
        ),
        sa.UniqueConstraint(
            "fencing_token", name=op.f("uq_plugin_revision_activation_fencing_token")
        ),
    )
    with op.batch_alter_table("plugin_revision_activation", schema=None) as batch_op:
        batch_op.create_index(
            "ix_plugin_activation_state", ["deployment_id", "status"], unique=False
        )

    op.create_table(
        "maibot_connection_state",
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("deployment_revision_id", sa.Uuid(), nullable=False),
        sa.Column("activation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "STOPPED",
                "CONNECTING",
                "CONNECTED",
                "BACKOFF",
                name="maibot_connection_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activation_id"],
            ["plugin_revision_activation.id"],
            name=op.f("fk_maibot_connection_state_activation_id_plugin_revision_activation"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["plugin_deployment.id"],
            name=op.f("fk_maibot_connection_state_deployment_id_plugin_deployment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deployment_revision_id"],
            ["plugin_deployment_revision.id"],
            name=op.f(
                "fk_maibot_connection_state_deployment_revision_id_plugin_deployment_revision"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maibot_connection_state")),
        sa.UniqueConstraint("deployment_id", name=op.f("uq_maibot_connection_state_deployment_id")),
    )
    op.create_table(
        "maibot_bridge_envelope",
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("deployment_revision_id", sa.Uuid(), nullable=False),
        sa.Column("activation_id", sa.Uuid(), nullable=False),
        sa.Column("bot_account_id", sa.Uuid(), nullable=True),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "TO_MAIBOT",
                "FROM_MAIBOT",
                name="maibot_bridge_direction",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "MESSAGE",
                "REPLY",
                "PROACTIVE",
                name="maibot_bridge_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("transport_message_id", sa.String(length=255), nullable=False),
        sa.Column("business_message_id", sa.String(length=600), nullable=True),
        sa.Column("reply_to_business_message_id", sa.String(length=600), nullable=True),
        sa.Column("source_event_id", sa.Uuid(), nullable=True),
        sa.Column("source_envelope_id", sa.Uuid(), nullable=True),
        sa.Column("actor_principal_id", sa.Uuid(), nullable=True),
        sa.Column("chatroom_id", sa.Uuid(), nullable=True),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("target_wxid", sa.String(length=255), nullable=True),
        sa.Column(
            "authorization_context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "envelope",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CLAIMED",
                "SENT",
                "ACKED",
                "RECEIVED",
                "ACCEPTED",
                "REJECTED",
                "EXPIRED",
                "CANCELLED",
                "FAILED_RETRYABLE",
                "FAILED_FINAL",
                name="maibot_bridge_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("acked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activation_id"],
            ["plugin_revision_activation.id"],
            name=op.f("fk_maibot_bridge_envelope_activation_id_plugin_revision_activation"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["actor_principal_id"],
            ["principal.id"],
            name=op.f("fk_maibot_bridge_envelope_actor_principal_id_principal"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["bot_account_id"],
            ["bot_account.id"],
            name=op.f("fk_maibot_bridge_envelope_bot_account_id_bot_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["chatroom_id"],
            ["chatroom.id"],
            name=op.f("fk_maibot_bridge_envelope_chatroom_id_chatroom"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_maibot_bridge_envelope_contact_id_contact"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["plugin_deployment.id"],
            name=op.f("fk_maibot_bridge_envelope_deployment_id_plugin_deployment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deployment_revision_id"],
            ["plugin_deployment_revision.id"],
            name=op.f(
                "fk_maibot_bridge_envelope_deployment_revision_id_plugin_deployment_revision"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_envelope_id"],
            ["maibot_bridge_envelope.id"],
            name=op.f("fk_maibot_bridge_envelope_source_envelope_id_maibot_bridge_envelope"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["normalized_event.id"],
            name=op.f("fk_maibot_bridge_envelope_source_event_id_normalized_event"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maibot_bridge_envelope")),
        sa.UniqueConstraint(
            "deployment_id",
            "source_event_id",
            name="uq_maibot_bridge_source_event",
        ),
        sa.UniqueConstraint(
            "deployment_id",
            "direction",
            "transport_message_id",
            name="uq_maibot_bridge_transport",
        ),
    )
    with op.batch_alter_table("maibot_bridge_envelope", schema=None) as batch_op:
        batch_op.create_index(
            "ix_maibot_bridge_business_message",
            ["deployment_id", "direction", "business_message_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_maibot_bridge_due",
            ["deployment_id", "status", "available_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("maibot_bridge_envelope", schema=None) as batch_op:
        batch_op.drop_index("ix_maibot_bridge_due")
        batch_op.drop_index("ix_maibot_bridge_business_message")

    op.drop_table("maibot_bridge_envelope")
    op.drop_table("maibot_connection_state")
    with op.batch_alter_table("plugin_revision_activation", schema=None) as batch_op:
        batch_op.drop_index("ix_plugin_activation_state")

    op.drop_table("plugin_revision_activation")
    with op.batch_alter_table("chatroom_membership", schema=None) as batch_op:
        batch_op.drop_index("ix_membership_active_member")

    op.drop_table("chatroom_membership")
    with op.batch_alter_table("plugin_deployment_revision", schema=None) as batch_op:
        batch_op.drop_index("ix_plugin_revision_package")

    op.drop_table("plugin_deployment_revision")
    with op.batch_alter_table("outbox_message", schema=None) as batch_op:
        batch_op.drop_index("ix_outbox_status_available")

    op.drop_table("outbox_message")
    with op.batch_alter_table("normalized_event", schema=None) as batch_op:
        batch_op.drop_index("ix_normalized_event_conversation")

    op.drop_table("normalized_event")
    op.drop_table("contact")
    op.drop_table("chatroom")
    with op.batch_alter_table("webhook_inbox", schema=None) as batch_op:
        batch_op.drop_index("ix_webhook_inbox_status_received")

    op.drop_table("webhook_inbox")
    op.drop_table("plugin_package_version")
    op.drop_table("plugin_deployment")
    with op.batch_alter_table("bot_account", schema=None) as batch_op:
        batch_op.drop_index("ix_bot_account_connection_status")

    op.drop_table("bot_account")
    with op.batch_alter_table("auth_security_event", schema=None) as batch_op:
        batch_op.drop_index("ix_auth_security_event_created")

    op.drop_table("auth_security_event")
    with op.batch_alter_table("acl_rule", schema=None) as batch_op:
        batch_op.drop_index("ix_acl_rule_scope")
        batch_op.drop_index("ix_acl_rule_lookup")

    op.drop_table("acl_rule")
    op.drop_table("rbac_user_role")
    op.drop_table("rbac_role_permission")
    with op.batch_alter_table("principal", schema=None) as batch_op:
        batch_op.drop_index("ix_principal_workspace_active")

    op.drop_table("principal")
    with op.batch_alter_table("policy_decision", schema=None) as batch_op:
        batch_op.drop_index("ix_policy_decision_trace_created")

    op.drop_table("policy_decision")
    op.drop_table("plugin")
    op.drop_table("gewe_connection")
    op.drop_table("auth_bootstrap_state")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_event_trace_created")

    op.drop_table("audit_event")
    with op.batch_alter_table("admin_session", schema=None) as batch_op:
        batch_op.drop_index("ix_admin_session_user_active")
        batch_op.drop_index("ix_admin_session_expiry")

    op.drop_table("admin_session")
    op.drop_table("acl_policy_state")
    op.drop_table("workspace")
    op.drop_table("rbac_role")
    op.drop_table("rbac_permission")
    with op.batch_alter_table("auth_login_throttle", schema=None) as batch_op:
        batch_op.drop_index("ix_auth_login_throttle_blocked")

    op.drop_table("auth_login_throttle")
    with op.batch_alter_table("admin_user", schema=None) as batch_op:
        batch_op.drop_index("ix_admin_user_status")

    op.drop_table("admin_user")
    # ### end Alembic commands ###
