"""single workspace and delivery receipts

Revision ID: 4868c0a12c0f
Revises: f2ed1f640367
Create Date: 2026-08-30 21:18:50.780449
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4868c0a12c0f"
down_revision: str | None = "f2ed1f640367"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_event_dispatch",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCEEDED",
                "DENIED",
                "REJECTED",
                "FAILED_RETRYABLE",
                name="plugin_event_dispatch_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("accepted_action_count", sa.Integer(), nullable=False),
        sa.Column("last_error_type", sa.String(length=120), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["plugin_deployment.id"],
            name=op.f("fk_plugin_event_dispatch_deployment_id_plugin_deployment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["normalized_event.id"],
            name=op.f("fk_plugin_event_dispatch_event_id_normalized_event"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["plugin_deployment_revision.id"],
            name=op.f("fk_plugin_event_dispatch_revision_id_plugin_deployment_revision"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_event_dispatch")),
        sa.UniqueConstraint(
            "event_id", "deployment_id", name=op.f("uq_plugin_event_dispatch_event_id")
        ),
    )
    with op.batch_alter_table("plugin_event_dispatch", schema=None) as batch_op:
        batch_op.create_index(
            "ix_plugin_event_dispatch_status", ["status", "updated_at"], unique=False
        )

    with op.batch_alter_table("outbox_message", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_attempt_started_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_attempt_finished_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("provider_message_id", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("provider_new_message_id", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("provider_create_time", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("provider_message_type", sa.Integer(), nullable=True))

    with op.batch_alter_table("workspace", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("singleton_key", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_workspace_singleton_key"), ["singleton_key"]
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_workspace_singleton_key_one"), "singleton_key = 1"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspace", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_workspace_singleton_key_one"), type_="check")
        batch_op.drop_constraint(batch_op.f("uq_workspace_singleton_key"), type_="unique")
        batch_op.drop_column("singleton_key")

    with op.batch_alter_table("outbox_message", schema=None) as batch_op:
        batch_op.drop_column("provider_message_type")
        batch_op.drop_column("provider_create_time")
        batch_op.drop_column("provider_new_message_id")
        batch_op.drop_column("provider_message_id")
        batch_op.drop_column("last_attempt_finished_at")
        batch_op.drop_column("last_attempt_started_at")

    with op.batch_alter_table("plugin_event_dispatch", schema=None) as batch_op:
        batch_op.drop_index("ix_plugin_event_dispatch_status")

    op.drop_table("plugin_event_dispatch")
    # ### end Alembic commands ###
