"""task agent state machine

Revision ID: f2ed1f640367
Revises: 486090cfcf32
Create Date: 2026-08-30 20:29:10.846806
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f2ed1f640367"
down_revision: str | None = "486090cfcf32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_definition",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("definition_key", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_agent_definition_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_definition")),
        sa.UniqueConstraint(
            "workspace_id", "definition_key", name=op.f("uq_agent_definition_workspace_id")
        ),
    )
    op.create_table(
        "agent_version",
        sa.Column("definition_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "specification",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("specification_sha256", sa.String(length=64), nullable=False),
        sa.Column("published_by_principal_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_agent_version_agent_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["agent_definition.id"],
            name=op.f("fk_agent_version_definition_id_agent_definition"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_principal_id"],
            ["principal.id"],
            name=op.f("fk_agent_version_published_by_principal_id_principal"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_version")),
        sa.UniqueConstraint(
            "definition_id", "version_number", name=op.f("uq_agent_version_definition_id")
        ),
    )
    with op.batch_alter_table("agent_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_agent_version_definition_published", ["definition_id", "published_at"], unique=False
        )

    op.create_table(
        "agent_session",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("requester_principal_id", sa.Uuid(), nullable=False),
        sa.Column(
            "task_scope",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("task_scope_sha256", sa.String(length=64), nullable=False),
        sa.Column("last_inbox_seq", sa.Integer(), nullable=False),
        sa.Column("last_event_seq", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last_event_seq >= 0", name=op.f("ck_agent_session_agent_session_event_seq_nonnegative")
        ),
        sa.CheckConstraint(
            "last_inbox_seq >= 0", name=op.f("ck_agent_session_agent_session_inbox_seq_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_version.id"],
            name=op.f("fk_agent_session_agent_version_id_agent_version"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requester_principal_id"],
            ["principal.id"],
            name=op.f("fk_agent_session_requester_principal_id_principal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_agent_session_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_session")),
    )
    with op.batch_alter_table("agent_session", schema=None) as batch_op:
        batch_op.create_index(
            "ix_agent_session_workspace_created", ["workspace_id", "created_at"], unique=False
        )

    op.create_table(
        "agent_run",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "input_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "WAITING_APPROVAL",
                "WAITING_USER",
                "PAUSED",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "EXPIRED",
                name="agent_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("active_slot", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(active_slot = 1 AND status IN "
            "('QUEUED', 'RUNNING', 'WAITING_APPROVAL', 'WAITING_USER', 'PAUSED')) "
            "OR (active_slot IS NULL AND status IN "
            "('COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED'))",
            name=op.f("ck_agent_run_agent_run_status_active_slot"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_session.id"],
            name=op.f("fk_agent_run_session_id_agent_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_run")),
        sa.UniqueConstraint("session_id", "active_slot", name="uq_agent_run_session_active"),
        sa.UniqueConstraint(
            "session_id", "idempotency_key", name="uq_agent_run_session_idempotency"
        ),
    )
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.create_index(
            "ix_agent_run_session_created", ["session_id", "created_at"], unique=False
        )

    op.create_table(
        "agent_pending_question",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("allowed_principal_id", sa.Uuid(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ANSWERED",
                "EXPIRED",
                "CANCELLED",
                name="agent_pending_question_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("open_slot", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answered_by_principal_id", sa.Uuid(), nullable=True),
        sa.Column(
            "answer_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("answer_sha256", sa.String(length=64), nullable=True),
        sa.Column("answer_inbox_seq", sa.Integer(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(open_slot = 1 AND status = 'PENDING') OR "
            "(open_slot IS NULL AND status IN ('ANSWERED', 'EXPIRED', 'CANCELLED'))",
            name=op.f("ck_agent_pending_question_agent_question_status_open_slot"),
        ),
        sa.ForeignKeyConstraint(
            ["allowed_principal_id"],
            ["principal.id"],
            name=op.f("fk_agent_pending_question_allowed_principal_id_principal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["answered_by_principal_id"],
            ["principal.id"],
            name=op.f("fk_agent_pending_question_answered_by_principal_id_principal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_run.id"],
            name=op.f("fk_agent_pending_question_run_id_agent_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_session.id"],
            name=op.f("fk_agent_pending_question_session_id_agent_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_pending_question")),
        sa.UniqueConstraint("run_id", "open_slot", name=op.f("uq_agent_pending_question_run_id")),
    )
    with op.batch_alter_table("agent_pending_question", schema=None) as batch_op:
        batch_op.create_index("ix_agent_question_due", ["status", "expires_at"], unique=False)

    op.create_table(
        "agent_event",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("question_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "SESSION_CREATED",
                "RUN_CREATED",
                "RUN_STATUS_CHANGED",
                "QUESTION_ASKED",
                "QUESTION_ANSWERED",
                name="agent_event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("seq >= 1", name=op.f("ck_agent_event_agent_event_seq_positive")),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["agent_pending_question.id"],
            name=op.f("fk_agent_event_question_id_agent_pending_question"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_run.id"],
            name=op.f("fk_agent_event_run_id_agent_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_session.id"],
            name=op.f("fk_agent_event_session_id_agent_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_event")),
        sa.UniqueConstraint("session_id", "seq", name=op.f("uq_agent_event_session_id")),
    )
    with op.batch_alter_table("agent_event", schema=None) as batch_op:
        batch_op.create_index("ix_agent_event_run", ["run_id", "seq"], unique=False)

    op.create_table(
        "agent_session_inbox",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "RUN_REQUEST",
                "QUESTION_ANSWER",
                name="agent_inbox_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("actor_principal_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "seq >= 1", name=op.f("ck_agent_session_inbox_agent_session_inbox_seq_positive")
        ),
        sa.ForeignKeyConstraint(
            ["actor_principal_id"],
            ["principal.id"],
            name=op.f("fk_agent_session_inbox_actor_principal_id_principal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["agent_pending_question.id"],
            name=op.f("fk_agent_session_inbox_question_id_agent_pending_question"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_run.id"],
            name=op.f("fk_agent_session_inbox_run_id_agent_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_session.id"],
            name=op.f("fk_agent_session_inbox_session_id_agent_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_session_inbox")),
        sa.UniqueConstraint("question_id", name=op.f("uq_agent_session_inbox_question_id")),
        sa.UniqueConstraint("session_id", "seq", name=op.f("uq_agent_session_inbox_session_id")),
    )
    with op.batch_alter_table("agent_session_inbox", schema=None) as batch_op:
        batch_op.create_index("ix_agent_session_inbox_run", ["run_id", "seq"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_session_inbox", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_session_inbox_run")

    op.drop_table("agent_session_inbox")
    with op.batch_alter_table("agent_event", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_event_run")

    op.drop_table("agent_event")
    with op.batch_alter_table("agent_pending_question", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_question_due")

    op.drop_table("agent_pending_question")
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_run_session_created")

    op.drop_table("agent_run")
    with op.batch_alter_table("agent_session", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_session_workspace_created")

    op.drop_table("agent_session")
    with op.batch_alter_table("agent_version", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_version_definition_published")

    op.drop_table("agent_version")
    op.drop_table("agent_definition")
    # ### end Alembic commands ###
